# Generated by Django 4.2.5 on 2023-10-05 19:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("destination", "0002_remove_destination_country_city_destination_city"),
        ("hotel", "0001_initial"),
        ("user", "0001_initial"),
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destinationreview",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="destination.destination",
            ),
        ),
        migrations.AlterField(
            model_name="destinationreview",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="destinationreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="hotelreview",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="hotel.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="hotelreview",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="hotelreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.userprofile"
            ),
        ),
    ]
