# Generated by Django 4.2.6 on 2023-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_dob_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imageUrl',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
    ]
