# Generated by Django 4.2.6 on 2023-10-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='backgroundUrl',
            field=models.ImageField(null=True, upload_to='user_background_images/'),
        ),
    ]
