# Generated by Django 4.2.6 on 2023-10-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganization',
            name='backgroundUrl',
            field=models.ImageField(null=True, upload_to='user_organization_bgimages/'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='tax',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='bio',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='imageUrl',
            field=models.ImageField(null=True, upload_to='user_organization_images/'),
        ),
    ]
