# Generated by Django 4.2.6 on 2023-10-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='owner',
            new_name='user',
        ),
    ]
