# Generated by Django 4.2.6 on 2023-10-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='room',
            name='imageUrl',
            field=models.ImageField(null=True, upload_to='room_images/'),
        ),
    ]
