# Generated by Django 4.2.6 on 2023-10-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotel_created_at_hotel_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='hotel.room'),
        ),
    ]
