# Generated by Django 4.2.6 on 2023-10-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_facility_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='room',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='hotel.room'),
            preserve_default=False,
        ),
    ]
