# Generated by Django 4.2.5 on 2023-10-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("country", "0003_country_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(max_length=500)),
                (
                    "imageUrl",
                    models.ImageField(null=True, upload_to="destination_images/"),
                ),
                ("address", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="country.country",
                    ),
                ),
            ],
        ),
    ]
