# Generated by Django 4.2.5 on 2023-10-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("country", "0003_country_description"),
        ("destination", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="country",
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="country.country",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="destination",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="destination.city",
            ),
        ),
    ]
