# Generated by Django 4.2.6 on 2023-10-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userorganization'),
        ('destination', '0002_remove_destination_country_city_destination_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userorganization'),
        ),
    ]
