# Generated by Django 4.2.6 on 2023-10-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_alter_country_description_alter_country_imageurl'),
        ('destination', '0004_alter_destination_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='country.country'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='destination.city'),
        ),
    ]
