# Generated by Django 4.2.6 on 2023-10-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0005_alter_city_country_alter_destination_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='contact',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
