# Generated by Django 4.2.5 on 2023-10-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_remove_booking_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
