# Generated by Django 4.2.5 on 2023-10-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_booking_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
