# Generated by Django 4.2.6 on 2023-10-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_is_approved_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='client',
            new_name='user',
        ),
    ]
