# Generated by Django 3.2.7 on 2023-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_country_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
