# Generated by Django 4.2.5 on 2023-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("country", "0003_country_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="description",
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="imageUrl",
            field=models.ImageField(default=1, upload_to="country_images/"),
            preserve_default=False,
        ),
    ]
